"""Add created_at to Reword

Revision ID: 4e95c445a573
Revises: fafb51758a07
Create Date: 2024-09-03 23:15:43.712980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e95c445a573'
down_revision = 'fafb51758a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
