"""add Person

Revision ID: 85c2723d4502
Revises: bac13ad9a4ee
Create Date: 2024-09-14 15:41:15.129333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c2723d4502'
down_revision = 'bac13ad9a4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.drop_column('point')

    # ### end Alembic commands ###
