"""Initial migration.

Revision ID: fafb51758a07
Revises: f3c3cd1770a4
Create Date: 2024-09-01 16:34:26.472560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafb51758a07'
down_revision = 'f3c3cd1770a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reword_kind', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reword', schema=None) as batch_op:
        batch_op.drop_column('reword_kind')

    # ### end Alembic commands ###
